# Optional config; scripts run fine without this file.
start_date: 2024-01-01
end_date: 2025-08-28
min_score: 50
query: "ai,llm,gpt,rag,transformers,diffusion"
only_show_hn: false
resolve_urls: false
method: "algolia"  # or "firebase"
