# config
start_date: 2023-01-01
end_date: 2025-08-28
min_score: 10
query: ""
only_show_hn: false
resolve_urls: false    # set to true to follow shorteners (slower)
method: "algolia"      # or "firebase"
out_prefix: "allgh23"

algolia_query: "github.com"
